// For dynamic dropdowns, where the options appear after you enter some text, we're going to Type some text, & then select from the options that are dynamically generated.
// As for the locator, we're going to use chain locators to get the options generated by the user input.
// As there are going to be multiple options returned, we will be using $$ to get the elements
// We assign the options/elements to an array, then loop through the array items.
// If one of the array items matches the text we specify, click that item.

describe("Dynamic dropdowns Smoke", async () => {
  it("Section 7 - Dynamic dropdowns", async () => {
    await browser.url("/AutomationPractice/");
    await $("#autocomplete").setValue("Ind");
    await browser.pause(3000);
    let items = await $$("[class='ui-menu-item'] div");
    for (let i = 0; i < (await items.length); i++) {
      if ((await items[i].getText()) === "India") {
        await items[i].click();
        await browser.pause(3000);
      }
    }
  });
});
